import React from 'react';
import './globals.css';
import type { Metadata } from 'next';
import Navigation from '@/src/components/navigation/navigation';

export const metadata: Metadata = {
    title: 'Mumble App',
    description: 'Generated by PixelPioneers',
};

export default function RootLayout({
    children,
    posts,
    users,
}: {
    children: React.ReactNode;
    posts: React.ReactNode;
    users: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className="bg-slate-100">
                <Navigation />
                <main className="my-l flex min-h-screen flex-col items-center justify-between">
                    {children}
                    {posts}
                    {users}
                </main>
            </body>
        </html>
    );
}
