import React from 'react';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Mumble App',
    description: 'Generated by PixelPioneers',
};

export default function RootLayout(
    { children }: { children: React.ReactNode },
    posts: React.ReactNode,
    users: React.ReactNode,
) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <main>
                    {children}
                    {posts}
                    {users}
                </main>
            </body>
        </html>
    );
}
